# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application_mode_selection_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from src.view.basic_ui import UI_MainPage
from src.view.batch_mode_window import Ui_BatchModeWindow


class Ui_ApplicationModeSelectionWindow(QMainWindow):
    def setupUi(self, ApplicationModeSelectionWindow):
        ApplicationModeSelectionWindow.setObjectName("ApplicationModeSelectionWindow")
        ApplicationModeSelectionWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ApplicationModeSelectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 180, 571, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 310, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_single_processing_window)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 310, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.open_batch_processing_window)
        ApplicationModeSelectionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ApplicationModeSelectionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ApplicationModeSelectionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ApplicationModeSelectionWindow)
        self.statusbar.setObjectName("statusbar")
        ApplicationModeSelectionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ApplicationModeSelectionWindow)
        QtCore.QMetaObject.connectSlotsByName(ApplicationModeSelectionWindow)

    def retranslateUi(self, ApplicationModeSelectionWindow):
        _translate = QtCore.QCoreApplication.translate
        ApplicationModeSelectionWindow.setWindowTitle(_translate("ApplicationModeSelectionWindow", "MainWindow"))
        self.label.setText(_translate("ApplicationModeSelectionWindow", "Tonation Recognition"))
        self.pushButton.setText(_translate("ApplicationModeSelectionWindow", "Single mode"))
        self.pushButton_2.setText(_translate("ApplicationModeSelectionWindow", "Batch mode"))


    def __init__(self):
        super(Ui_ApplicationModeSelectionWindow, self).__init__()
        self.main_window = QMainWindow()
        self.setupUi(self.main_window)
        self.main_window.show()


    def open_single_processing_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = UI_MainPage()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_batch_processing_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_BatchModeWindow()
        self.ui.setupUi(self.window)
        self.window.show()
