# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_mode_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QFileDialog, QListWidgetItem

from src.algorithms.algorithm_manager import AlgorithmManager
from src.file_manager.file_manager import MidiReader, FileInfo
from src.model.definitions import Note, MIDI_FILES_PATH, RHYTHMIC_VALUES, RhythmicValues, SampleMode, AlgorithmInfo, \
    Algorithm, Profile, BATCH_PROCESSING_SAVE_FILES_PATH
from pathlib import Path


class Ui_BatchModeWindow(object):
    def setupUi(self, BatchModeWindow):
        BatchModeWindow.setObjectName("BatchModeWindow")
        BatchModeWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BatchModeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(30, 120, 421, 321))
        self.file_list.setObjectName("file_list")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.load_files_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_files_button.setGeometry(QtCore.QRect(480, 120, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.load_files_button.setFont(font)
        self.load_files_button.setObjectName("load_files_button")
        self.load_files_button.clicked.connect(self.load_file_button_clicker)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 350, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.parallel_tonation_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.parallel_tonation_combo_box.setGeometry(QtCore.QRect(480, 390, 251, 51))
        self.parallel_tonation_combo_box.setObjectName("parallel_tonation_combo_box")
        for note in Note:
            self.parallel_tonation_combo_box.addItem(note.name, note)
        self.parallel_tonation_combo_box.currentIndexChanged.connect(self.on_parallel_tonation_selection_changed)
        self.main_tonation_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.main_tonation_combo_box.setGeometry(QtCore.QRect(480, 280, 251, 51))
        self.main_tonation_combo_box.setObjectName("main_tonation_combo_box")
        for note in Note:
            self.main_tonation_combo_box.addItem(note.name, note)
        self.main_tonation_combo_box.currentIndexChanged.connect(self.on_main_tonation_selection_changed)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 240, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(30, 460, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.calculate_button.setFont(font)
        self.calculate_button.setObjectName("calculate_button")
        self.calculate_button.clicked.connect(self.on_calculate_button_clicked)
        BatchModeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BatchModeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        BatchModeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BatchModeWindow)
        self.statusbar.setObjectName("statusbar")
        BatchModeWindow.setStatusBar(self.statusbar)

        #Logic related variables
        self.selected_main_tonation = self.main_tonation_combo_box.itemData(0)
        self.selected_parallel_tonation = self.parallel_tonation_combo_box.itemData(0)
        self.track_list = []
        self.algorithm_manager = AlgorithmManager()

        self.retranslateUi(BatchModeWindow)
        QtCore.QMetaObject.connectSlotsByName(BatchModeWindow)

    def retranslateUi(self, BatchModeWindow):
        _translate = QtCore.QCoreApplication.translate
        BatchModeWindow.setWindowTitle(_translate("BatchModeWindow", "MainWindow"))
        self.label.setText(_translate("BatchModeWindow", "Chosen files"))
        self.load_files_button.setText(_translate("BatchModeWindow", "Load"))
        self.label_3.setText(_translate("BatchModeWindow", "Parallel tonation"))
        self.label_4.setText(_translate("BatchModeWindow", "Main tonation"))
        self.calculate_button.setText(_translate("BatchModeWindow", "Calculate"))


    def on_main_tonation_selection_changed(self, index):
        self.selected_main_tonation = self.main_tonation_combo_box.itemData(index)

    def on_parallel_tonation_selection_changed(self, index):
        self.selected_parallel_tonation = self.parallel_tonation_combo_box.itemData(index)

    def on_calculate_button_clicked(self):
        self.calculate_all_input_combinations()

    def load_file_button_clicker(self):
        self.filenames, _ = QFileDialog.getOpenFileNames(self.centralwidget, "Open MIDI file", MIDI_FILES_PATH, "MIDI files (*.mid);;")
        file_number = 0
        if len(self.filenames) > 0:
            self.track_list.clear()
            self.files = []
            for filename in self.filenames:
                reader = MidiReader()
                self.read_midi(filename, reader, file_number)
                file_number += 1
            self.setup_file_list()

    def read_midi(self, filename, reader, file_number):
        file, track_manager = reader.read_file(filename)
        self.files.append(FileInfo(file, track_manager, False, file_number))

    def setup_file_list(self):
        self.file_list.clear()
        for filename in self.filenames:
            item = QListWidgetItem(filename)
            self.file_list.addItem(item)
        self.file_list.itemClicked.connect(self.file_list_selection_changed)


    def file_list_selection_changed(self, item):
        self.is_file_selected = True
        self.selected_file_number = next(file_info for file_info in self.files if file_info.file.filename == item.text()).file_number
        item.setBackground(QColor('green'))
        for index in range(self.file_list.count()):
            if self.file_list.item(index).text() != item.text():
                self.file_list.item(index).setBackground(QColor('white'))
        ##TODO
        #tu trzeba ustawić po kolei wszystkie wartości rytmiczne
        # self.max_number_of_notes_to_check = self.files[self.selected_file_number]\
        #     .track_manager.calculate_base_rhythmic_value_multiplicity(RhythmicValues.QUARTER.name)
        # # self.max_number_of_notes.setText(str(self.max_number_of_notes_to_check))
        # self.global_track_length = self.files[self.selected_file_number].track_manager.get_operable_range_of_all_tracks()
        # self.setup_track_list()
        # self.files[self.selected_file_number].track_manager.activate_all_tracks()
        # for i in range(self.track_list.count()):
        #     self.track_list.item(i).setBackground(QColor('green'))
        # self.is_track_selected = True


    def calculate_all_input_combinations(self):
        algorithm_infos = []
        for sample_mode in SampleMode:
            algorithm_infos.append(AlgorithmInfo(Algorithm.SIGNATURE_MODE_AXIS, sample_mode, None))
            for profile in Profile:
                algorithm_infos.append(AlgorithmInfo(Algorithm.SIGNATURE_TONAL_PROFILES, sample_mode, profile))
        total_results = []
        # for rhytmic_value in RhythmicValues:
        #     if rhytmic_value != RhythmicValues.LOWER_THAN_SIXTY_FOUR:
        # number_of_units = int(self.number_of_units.toPlainText())
        number_of_units = 1
        #TODO
        # tu musi być samo rhytmic_value !!!!!!!!
        max_number_of_notes_to_check = self.files[self.selected_file_number].track_manager.calculate_base_rhythmic_value_multiplicity(RhythmicValues.QUARTER)
        number_of_samples = int(max_number_of_notes_to_check / number_of_units)
        remainder_size = max_number_of_notes_to_check % number_of_units
        GOAL_TONATION = self.selected_main_tonation.name
        PARALLEL_TONATION = self.selected_parallel_tonation.name
        algorithms_performances = []
        for alg_inf in algorithm_infos:
            actual_window_start = 0
            actual_window_end = 0
            for actual_position in range(0, number_of_samples):
                actual_window_end += number_of_units
                print("actual_window_end: " + str(actual_window_end))
                #TODO
                # tu musi być rhytmic_value.name !!!!!!!!
                res = self.calculate_results_batch_mode(alg_inf, actual_window_start, actual_window_end, alg_inf.sample_calculation_mode, RhythmicValues.QUARTER.name)
                if res == GOAL_TONATION:
                    algorithms_performances.append({"algorithm":alg_inf.algorithm_type, "sample_calculation_type":alg_inf.sample_calculation_mode,
                                                    "profile":alg_inf.profile, "performance":actual_window_end})
                    break
                elif res == PARALLEL_TONATION:
                    algorithms_performances.append({"algorithm":alg_inf.algorithm_type, "sample_calculation_type":alg_inf.sample_calculation_mode,
                                                    "profile":alg_inf.profile, "performance":actual_window_end, "parallel_tonation":True})
                    break

            if remainder_size > 0:
                res = self.calculate_results_batch_mode(alg_inf, actual_window_start, actual_window_end + remainder_size, alg_inf.sample_calculation_mode, RhythmicValues.QUARTER.name)
                if res == GOAL_TONATION:
                    algorithms_performances.append({"algorithm":alg_inf.algorithm_type, "sample_calculation_type":alg_inf.sample_calculation_mode,
                                                    "profile":alg_inf.profile, "performance":actual_window_end})
                    break
                elif res == PARALLEL_TONATION:
                    algorithms_performances.append({"algorithm":alg_inf.algorithm_type, "sample_calculation_type":alg_inf.sample_calculation_mode,
                                                    "profile":alg_inf.profile, "performance":actual_window_end, "parallel_tonation":True})
                    break
        total_results.append({"rhytmic_value":"QUARTER", "result":algorithms_performances})
        with open(BATCH_PROCESSING_SAVE_FILES_PATH + "\\" + Path(self.files[self.selected_file_number].file.filename).stem + ".xlsx", 'w') as f:
            for res in total_results:
                for key, value in res.items():
                    f.write('%s:%s' % (key, value))
                f.write("\n\n\n")
        return

    def get_filename(self, file_path):
        elements = file_path.split("//")
        return elements[len(elements) - 1]

    def calculate_results_batch_mode(self, algorithm_info, actual_window_start, actual_window_end, sample_calculation_mode, min_rhytmic_value):
        self.files[self.selected_file_number].track_manager.activate_all_tracks()
        result_information, signature, same_axes, mode_angle_equal_zero = self.algorithm_manager.execute_algorithm(algorithm_info,
                                                                                      self.files[
                                                                                          self.selected_file_number].track_manager.calculate_sample_vector(
                                                                                          actual_window_start,
                                                                                          actual_window_end,
                                                                                          sample_calculation_mode,
                                                                                          min_rhytmic_value))

        return result_information
